name: Nexus
version: 0.1
description: Nexus block protection
main: com.github.itsnickbarry.nexus.NexusMain

commands:
  nexus:
    aliases: [n]
    
permissions:
  nexus.*:
    default: false
    children:
      nexus.admin: false
      nexus.create: true
      nexus.destroy: true
